"""generate token and confirm

Revision ID: 95371392b782
Revises: ba741bb6b4c7
Create Date: 2023-02-12 13:22:53.464797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95371392b782'
down_revision = 'ba741bb6b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
